### ISSUE TITLE
Credits, what about Rochet2?

### ISSUE THREAD

**Issue by Helias** [poszer/Multi-Vendor-AzerothCore-Patch#2]
Credits, what about Rochet2?

![image](https://user-images.githubusercontent.com/519778/85387995-d5a5b880-b545-11ea-85e7-ebcb09acbf8a.png)

**Comment by ELdoBA** [comment]
> Credits, what about Rochet2?
> 
> ![image](https://user-images.githubusercontent.com/519778/85387995-d5a5b880-b545-11ea-85e7-ebcb09acbf8a.png)

I think you should first check repos under your organization, and revert commits which removing credits of authors. Than you have permissions, to comment in that way. 

https://github.com/azerothcore/mod-starter-guild/blob/cf642c2aa7b80f748ae5c46613b12acf9d28fbbd/README.md

Before:
![Screenshot_1](https://user-images.githubusercontent.com/41213210/85394883-8feded80-b54f-11ea-877e-cfcb7ce220bf.png)
Now:
![Screenshot_2](https://user-images.githubusercontent.com/41213210/85394953-b01dac80-b54f-11ea-8a1b-0dc9530bb3ab.png)
